# https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      TF_ACTIONS_WORKING_DIR:
        required: true
        type: string
      AWS_REGION:
        required: false
        type: string  
        default: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  reuseable_terraform_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.TF_ACTIONS_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
  
      - uses: hashicorp/setup-terraform@v2
  
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false